django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pages.urls")),
]

pages/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import HomePageView, Success
from employees.views import (
    EmployeeLogoutView,
    EmployeePayslipListView,
    MyPayslipDetailView,
    SignUpView,
    EmployeeLoginView,
    EmployeeDashboardView,
    EmployeeBankUpdateView,
    EmployeeHomePageView,
    EmployeeProfileView,
)

from hr_dashboard.views import (
    AdminLoginView,
    AdminLogoutView,
    CombinedDepartmentView,
    HRDashboardView,
    EmployeeListView,
    # Unfixed
    DeductionCreateView,
    DeductionListView,
    EmployeeProfileView,
    VerificationCodeByDepartmentListView,
    VerificationCodeListView,
    PayslipCreateView,
    PayslipDetailView,
    PayslipListView,
)
from django.contrib.auth.views import LoginView


urlpatterns = [
    # Employee URLS
    path("employee/", EmployeeHomePageView.as_view(), name="employee_home"),
    path("signup/", SignUpView.as_view(), name="employee_signup"),
    path(
        "employee-login/",
        EmployeeLoginView.as_view(),
        name="employee_login",
    ),
    path(
        "password-change/",
        auth_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password-change/done/",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("userlogout/", EmployeeLogoutView.as_view(), name="employee_logout"),
    path("your-dashboard/", EmployeeDashboardView.as_view(), name="employee_dashboard"),
    path("my-profile/", EmployeeProfileView.as_view(), name="employee_details"),
    path("user/", EmployeeDashboardView.as_view(), name="user"),
    path(
        "update-bank-details/",
        EmployeeBankUpdateView.as_view(),
        name="update_bank_details",
    ),
    path(
        "my-payslips/", EmployeePayslipListView.as_view(), name="employee_payslip_list"
    ),
    path(
        "my_payslip/<int:pk>/", MyPayslipDetailView.as_view(), name="my_payslip_detail"
    ),
    # HR Urls
    path("home/", HomePageView.as_view(), name="home"),
    path("success/", Success.as_view(), name="success"),
    path("", AdminLoginView.as_view(), name="admin_login"),
    path("dashboard/", HRDashboardView.as_view(), name="dashboard"),
    path("adminlogout/", AdminLogoutView.as_view(), name="admin_logout"),
    path("employee-registry/", EmployeeListView.as_view(), name="admin_employee_list"),
    path(
        "adminview-employees/<int:pk>/",
        EmployeeProfileView.as_view(),
        name="employee_profile",
    ),
    path(
        "departments/",
        CombinedDepartmentView.as_view(),
        name="department",
    ),
    path(
        "verification-codes/",
        VerificationCodeListView.as_view(),
        name="verification_codes",
    ),
    path(
        "verification_codes/<str:department_name>/",
        VerificationCodeByDepartmentListView.as_view(),
        name="codes_by_department",
    ),
    path("deductions/add/", DeductionCreateView.as_view(), name="deduction_add"),
    path("deductions/", DeductionListView.as_view(), name="deduction_list"),
    path("payslips/generate/", PayslipCreateView.as_view(), name="generate_payslip"),
    path("payslips/<int:pk>/", PayslipDetailView.as_view(), name="payslip_detail"),
    path("dashboard/payslips-list", PayslipListView.as_view(), name="all_payslip_list"),
]

employees/models.py
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.db import models
from django.core.validators import RegexValidator


# generate an employee ID - last 2 digit of current year and 4 random numbers
class Employee(AbstractUser):
    email = models.EmailField(unique=True)
    employee_id = models.CharField(max_length=6, unique=True, blank=True, null=True)
    mobile_number = models.PositiveBigIntegerField(blank=True, null=True)
    bank = models.ForeignKey("banklist_api.Bank", on_delete=models.SET_NULL, null=True)
    home_address = models.TextField(blank=True, null=True)
    account_name = models.CharField(max_length=255, blank=True, null=True)
    basic_salary = models.DecimalField(
        max_digits=14, decimal_places=2, default=0, null=True, blank=True
    )
    is_salary_set = models.BooleanField(default=False)
    department = models.ForeignKey(
        "hr_dashboard.Department", on_delete=models.SET_NULL, null=True, blank=True
    )
    account_number = models.CharField(
        max_length=10,
        blank=True,
        null=True,
        validators=[
            RegexValidator(
                regex="^\d{10}$",
                message="Account number must be exactly 10 digits",
                code="invalid_account_number",
            )
        ],
    )

    # Override the groups and user_permissions fields
    groups = models.ManyToManyField(Group, blank=True, related_name="employee_set")
    user_permissions = models.ManyToManyField(
        Permission, blank=True, related_name="employee_set"
    )

hr_dashboard/models.py
import uuid
from django.db import models
from django.urls import reverse
from employees.models import Employee
from django.utils import timezone


MONTH_CHOICES = [
    (1, "January"),
    (2, "February"),
    (3, "March"),
    (4, "April"),
    (5, "May"),
    (6, "June"),
    (7, "July"),
    (8, "August"),
    (9, "September"),
    (10, "October"),
    (11, "November"),
    (12, "December"),
]

"""Creating a Departemnt will generate multiple unique codes that will be used for verifcation on sign up"""


class Department(models.Model):
    name = models.CharField(max_length=100, unique=True)
    row = models.IntegerField()
    basic_pay = models.DecimalField(
        max_digits=14, decimal_places=2, default=0, null=True, blank=True
    )

    def get_verification_codes(self):
        return self.verification_codes.all()

    def save(self, *args, **kwargs):
        # Check if the instance already exists in the database
        if self.pk:
            old_department = Department.objects.get(pk=self.pk)
            difference = self.row - old_department.row
        else:
            difference = self.row

        super().save(*args, **kwargs)

        # Only create additional VerificationCode instances if there's an increase
        if difference > 0:
            for _ in range(difference):
                VerificationCode.objects.create(
                    department=self, code=str(uuid.uuid4())[:8]
                )


class VerificationCode(models.Model):
    UNUSED = "Unused"
    ISSUED = "Issued"
    STATUS_CHOICES = [
        (UNUSED, "Unused"),
        (ISSUED, "Issued"),
    ]

    department = models.ForeignKey(
        Department, related_name="verification_codes", on_delete=models.CASCADE
    )
    code = models.CharField(max_length=10, unique=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default=UNUSED)
    used_by = models.OneToOneField(
        Employee, null=True, blank=True, on_delete=models.SET_NULL
    )


class Deduction(models.Model):
    TAX = "TAX"
    DEBT = "DEBT"
    ABSENCE = "ABSENCE"
    TURNOVER = "TURNOVER"
    SALARY_ADVANCE = "SALARY_ADVANCE"
    OTHERS = "OTHERS"

    DEDUCTION_TYPES = [
        (TAX, "Tax"),
        (DEBT, "Shortfall"),
        (ABSENCE, "Absence Penalty"),
        (SALARY_ADVANCE, "Salary Advance"),
        (OTHERS, "Others"),
    ]
    type = models.CharField(max_length=20, choices=DEDUCTION_TYPES)
    description = models.TextField(null=True, blank=True)
    amount = models.DecimalField(max_digits=14, decimal_places=2, default=0)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    month = models.PositiveIntegerField(choices=MONTH_CHOICES)
    year = models.PositiveIntegerField(default=timezone.now().year)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.get_type_display()} - {self.description}"


class Payslip(models.Model):
    PENDING = "Pending"
    UNPAID = "Unpaid"
    PAID = "Paid"
    STATUS = [(PENDING, "Pending"), (UNPAID, "Unpaid"), (PAID, "Paid")]

    employee = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True)
    generated_on = models.DateTimeField(auto_now_add=True)
    month = models.PositiveIntegerField(choices=MONTH_CHOICES, null=True, blank=True)
    year = models.PositiveIntegerField(
        default=timezone.now().year, null=True, blank=True
    )

    basic_salary_at_time_of_generation = models.DecimalField(
        max_digits=14, decimal_places=2
    )
    bonuses = models.DecimalField(max_digits=14, decimal_places=2, default=0)
    status = models.CharField(max_length=20, choices=STATUS, default=PENDING)

    class Meta:
        unique_together = ["employee", "month", "year"]

    @property
    def total_deductions(self):
        deductions_for_month = Deduction.objects.filter(
            employee=self.employee, month=self.month, year=self.year
        )
        total = deductions_for_month.aggregate(sum=models.Sum("amount"))["sum"] or 0
        return total

    @property
    def net_pay(self):
        basic_salary = self.basic_salary_at_time_of_generation or 0
        return basic_salary + self.bonuses - self.total_deductions

    def get_payslip_id(self):
        return f"{self.employee.employee_id}{self.month:02}{str(self.year)[2:]}"

    def __str__(self):
        return f"{self.employee.first_name} {self.employee.last_name} - {self.date} - Net Pay:{self.net_pay} - Payslip ID:{self.get_payslip_id()}"

    def get_absolute_url(self):
        return reverse("payslip", kwargs={"pk": self.pk})

employees/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError
from hr_dashboard.models import Department, VerificationCode
from .models import Employee


class EmployeeSignUpForm(UserCreationForm):
    full_name = forms.CharField(max_length=150, label="Full Name")
    verification_code = forms.CharField()

    class Meta:
        model = Employee
        fields = (
            "email",
            "full_name",
            "verification_code",
            "password1",
            "password2",
        )

    def clean_full_name(self):
        full_name = self.cleaned_data.get("full_name")
        names = full_name.split()
        if len(names) < 2:
            raise ValidationError("Please enter both first and last name.")
        return full_name

    def clean_verification_code(self):
        code = self.cleaned_data.get("verification_code")
        try:
            verification_code_instance = VerificationCode.objects.get(code=code)
        except VerificationCode.DoesNotExist:
            raise forms.ValidationError("Invalid verification code.")
        if verification_code_instance.status == VerificationCode.ISSUED:
            raise forms.ValidationError("This verification code has already been used.")

        return code

    def save(self, commit=True):
        user = super().save(
            commit=False
        )  # Prepare the user instance but don't save to DB yet
        names = self.cleaned_data["full_name"].split()
        user.first_name = names[0]
        user.last_name = " ".join(names[1:])
        return user


# Employee bank details form
class EmployeeBankDetailsForm(UserChangeForm):
    password = None

    class Meta:
        model = Employee
        fields = (
            "bank",
            "account_name",
            "account_number",
        )

employees/views.py
from datetime import datetime

from hr_dashboard.models import VerificationCode
from .models import Employee
from .forms import EmployeeSignUpForm, EmployeeBankDetailsForm
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView, UpdateView, ListView, DetailView
import random
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.apps import apps

Payslip = apps.get_model("hr_dashboard", "Payslip")
Deduction = apps.get_model("hr_dashboard", "Deduction")


class EmployeeHomePageView(TemplateView):
    template_name = "employee/employee_home.html"


class EmployeeLoginView(auth_views.LoginView):
    template_name = "registration/login.html"

    def get_success_url(self):
        return reverse_lazy("employee_dashboard")


class SignUpView(CreateView):
    form_class = EmployeeSignUpForm
    template_name = "registration/signup.html"

    def generate_unique_employee_id(self):
        year_part = str(datetime.now().year)[2:]
        while True:
            random_part = f"{random.randint(0, 9999):04}"  # Ensure a 4-digit number
            new_id = f"{year_part}{random_part}"
            if not Employee.objects.filter(employee_id=new_id).exists():
                return new_id

    def form_valid(self, form):
        user = form.save(commit=False)
        user.username = user.email  # Set username to email
        user.employee_id = self.generate_unique_employee_id()

        # Fetch the verification code instance
        code_instance = VerificationCode.objects.get(
            code=form.cleaned_data.get("verification_code")
        )
        user.department = code_instance.department  # Assign the department

        user.save()  # Save user to DB

        # Update VerificationCode instance
        code_instance.used_by = user
        code_instance.status = VerificationCode.ISSUED
        code_instance.save()

        messages.success(self.request, "Thank You")
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy("success")


class EmployeeLogoutView(auth_views.LogoutView):
    next_page = "employee_home"


class EmployeeDashboardView(LoginRequiredMixin, TemplateView):
    template_name = "employee/employee_dashboard.html"


class EmployeeProfileView(LoginRequiredMixin, TemplateView):
    template_name = "employee/employee_details.html"


class EmployeePayslipListView(LoginRequiredMixin, ListView):
    model = Payslip
    template_name = "employee/employee_payslip_list.html"

    def get_queryset(self):
        return Payslip.objects.filter(employee=self.request.user).order_by("-date")


class MyPayslipDetailView(LoginRequiredMixin, DetailView):
    model = Payslip
    template_name = "employee/my_payslip_details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["company_name"] = self.request.tenant.name
        context["deductions"] = Deduction.objects.filter(
            employee=self.object.employee,
            month=self.object.month,
            year=self.object.year,
        )
        return context


class EmployeeBankUpdateView(LoginRequiredMixin, UpdateView):
    model = Employee
    form_class = EmployeeBankDetailsForm
    template_name = "employee/update_bank_details.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy("success")

templates/employee/employee_payslip_list.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Payslip List</title>
    <link rel="stylesheet" href="{% static 'css/tailwind.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/nav.css' %}"/>
    <script defer src="{% static 'js/alpine.js' %}"></script>
  </head>
  <body class="bg-gray">
    <div class="preloader">
        <img src="{% static 'img/synthx2.png' %}" alt="Logo" class="bounce-logo">
    </div>
      <header x-data="{navbarOpen: false}">
        
        <div class="mx w-full px-2 xl:container mt-10">
          <div
            class="flex items-center justify-between bg-transparent px-4 xl:px-[30px]"
          >
            <div class="mr-4 max-w-[100px] lg:mr-12">
              <a href="javascript:void(0)" class="block py-4">
                <img class="bounce-logo" width="100" height="20" src="{% static 'img/synthx2.png' %}" alt="logo" />
              </a>
            </div>
  
            <div class="flex w-full items-center justify-end ml-20">
                <div class="flex items-center justify-end">
                    <div class="flex items-center">

                        <div class="relative w-full max-w-[120px] lg:block">
                            <input
                              type="text"
                              placeholder="Search..."
                              class="h-9 w-full rounded border border-secondary bg-white bg-opacity-[8%] pr-4 pl-5 text-sm font-medium text-secondary placeholder placeholder-opacity-50 outline-none focus:border-success"
                            />
                            <button
                              class="absolute left-4 top-1/2 -translate-y-1/2 text-white opacity-50"
                            >
                              <svg
                                width="14"
                                height="14"
                                viewBox="0 0 14 14"
                                fill="none"
                                xmlns="http://www.w3.org/2000/svg"
                              >
                                <path
                                  fill-rule="evenodd"
                                  clip-rule="evenodd"
                                  d="M6.41666 2.33268C4.16149 2.33268 2.33332 4.16085 2.33332 6.41602C2.33332 8.67118 4.16149 10.4993 6.41666 10.4993C8.67182 10.4993 10.5 8.67118 10.5 6.41602C10.5 4.16085 8.67182 2.33268 6.41666 2.33268ZM1.16666 6.41602C1.16666 3.51652 3.51716 1.16602 6.41666 1.16602C9.31615 1.16602 11.6667 3.51652 11.6667 6.41602C11.6667 9.31551 9.31615 11.666 6.41666 11.666C3.51716 11.666 1.16666 9.31551 1.16666 6.41602Z"
                                  fill="currentColor"
                                />
                                <path
                                  fill-rule="evenodd"
                                  clip-rule="evenodd"
                                  d="M9.3 9.29976C9.52781 9.07195 9.89716 9.07195 10.125 9.29976L12.6625 11.8373C12.8903 12.0651 12.8903 12.4344 12.6625 12.6622C12.4347 12.89 12.0653 12.89 11.8375 12.6622L9.3 10.1247C9.0722 9.89691 9.0722 9.52757 9.3 9.29976Z"
                                  fill="currentColor"
                                />
                              </svg>
                            </button>
                          </div>
                        <div
                          @click.outside="navbarOpen = false"
                          class="group relative"
                        >
                          <button
                            @click="navbarOpen = !navbarOpen"
                            class="flex h-9 w-9 items-center justify-center rounded bg-white bg-opacity-[8%] text-white"
                          >
                            <svg
                              width="20"
                              height="20"
                              viewBox="0 0 20 20"
                              fill="none"
                              xmlns="http://www.w3.org/2000/svg"
                            >
                              <path
                                fill-rule="evenodd"
                                clip-rule="evenodd"
                                d="M1.45833 10.0007C1.45833 9.42535 1.9247 8.95898 2.49999 8.95898H17.5C18.0753 8.95898 18.5417 9.42535 18.5417 10.0007C18.5417 10.5759 18.0753 11.0423 17.5 11.0423H2.49999C1.9247 11.0423 1.45833 10.5759 1.45833 10.0007Z"
                                fill="#0b6e4f"
                              />
                              <path
                                fill-rule="evenodd"
                                clip-rule="evenodd"
                                d="M1.45833 5.00065C1.45833 4.42535 1.9247 3.95898 2.49999 3.95898H17.5C18.0753 3.95898 18.5417 4.42535 18.5417 5.00065C18.5417 5.57595 18.0753 6.04232 17.5 6.04232H2.49999C1.9247 6.04232 1.45833 5.57595 1.45833 5.00065Z"
                                fill="#0b6e4f"
                              />
                              <path
                                fill-rule="evenodd"
                                clip-rule="evenodd"
                                d="M1.45833 15.0007C1.45833 14.4254 1.9247 13.959 2.49999 13.959H17.5C18.0753 13.959 18.5417 14.4254 18.5417 15.0007C18.5417 15.5759 18.0753 16.0423 17.5 16.0423H2.49999C1.9247 16.0423 1.45833 15.5759 1.45833 15.0007Z"
                                fill="#0b6e4f"
                              />
                            </svg>
                          </button>
                          <nav
                            :class="navbarOpen ? 'visible opacity-100 top-full' : 'invisible opacity-0 top-[120%]'"
                            class="absolute left-0 mt-2 w-[100x] rounded bg-primary shadow-card-2 duration-200"
                          >
                            <ul class="space-y-5 py-6 px-5">
                              <li>
                                <a
                                  href="{% url 'employee_dashboard' %}"
                                  class="relative block text-sm font-medium text-white opacity-70 duration-200 hover:opacity-100"
                                >
                                <svg  width="20" height="20" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="white"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <title></title> <g fill="none" fill-rule="evenodd" id="页面-1" stroke="none" stroke-width="1"> <g id="导航图标" transform="translate(-26.000000, -15.000000)"> <g id="编组" transform="translate(26.000000, 15.000000)"> <rect fill="#FFFFFF" fill-opacity="0.01" fill-rule="nonzero" height="24" id="矩形" width="24" x="0" y="0"></rect> <polygon id="路径" points="4.5 9 4.5 21 19.5 21 19.5 9 12 3"></polygon> <polygon id="路径" points="4.5 21 4.5 9 2 11 12 3 22 11 19.5 9 19.5 21" stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></polygon> <polygon id="路径" points="9.5 14.5 9.5 21 14.5 21 14.5 14.5" stroke="white" stroke-linejoin="round" stroke-width="1.5"></polygon> <line id="路径" stroke="white" stroke-linecap="round" stroke-width="1.5" x1="4.5" x2="19.5" y1="21" y2="21"></line> </g> </g> </g> </g></svg>
                                </a>
                              </li>
                              <li>
                                <a
                                  href="{% url 'employee_logout' %}"
                                  class="relative block text-sm font-medium text-white opacity-70 duration-200 hover:opacity-100"
                                >
                                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M21 12L13 12" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M18 15L20.913 12.087V12.087C20.961 12.039 20.961 11.961 20.913 11.913V11.913L18 9" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M16 5V4.5V4.5C16 3.67157 15.3284 3 14.5 3H5C3.89543 3 3 3.89543 3 5V19C3 20.1046 3.89543 21 5 21H14.5C15.3284 21 16 20.3284 16 19.5V19.5V19" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
                                </a>
                              </li>
                            </ul>
                          </nav>
                        </div>
        
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </header>
      <!-- ====== Page Title Section Start -->
        <section class="py-5 bg-transparent rounded-lg mx-2 mb-4"> 
            <div class="mx-auto px-4 sm:container">
            <div class="border-secondary border-l-[5px] pl-5 ease-linear duration-1000">
                <h2 class="text-xl font-semibold text-black">
                    Payslip List
                </h2>
                <p class="text-body-color text-xs font-medium">
                    Browse through your monthly earnings and deductions. 
                </p>
            </div>
            </div>
        </section>
    <!-- ====== Horizontal Menu Section Start -->

    <section class="relative z-10 overflow-hidden lg:py-[50px]">
        <div class="container mx-auto">
          <div>
            <div class="border-stroke max-w-[370px] border py-[10px]">
                {% for payslip in object_list %}
              <div
                class="flex items-center justify-between py-[10px] pl-2 pr-4 hover:bg-gray-2 border-b border-stroke"
              >
                <div class="flex items-center">
                  <div class="mr-3">
                    <p class="bg-danger text-black inline-flex text-xs text-danger">
                      .
                    </p>
                  </div>
                  
                  <div>
                    <h4 class="text-base font-medium text-black">{{ payslip.get_month_display }} {{ payslip.year }}</h4>
                    <p class="text-body-color text-base">₦{{ payslip.net_pay|intcomma }}</p>
                  </div>
                </div>
                <div>
                  <div x-data="{openDropDown: false}" class="relative">
                    <button
                      @click="openDropDown = !openDropDown"
                      class="text-body-color"
                    >
                      <svg
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          fill-rule="evenodd"
                          clip-rule="evenodd"
                          d="M10 12C10 10.8954 10.8954 10 12 10C13.1046 10 14 10.8954 14 12C14 13.1046 13.1046 14 12 14C10.8954 14 10 13.1046 10 12Z"
                          fill="#637381"
                        />
                        <path
                          fill-rule="evenodd"
                          clip-rule="evenodd"
                          d="M10 5C10 3.89543 10.8954 3 12 3C13.1046 3 14 3.89543 14 5C14 6.10457 13.1046 7 12 7C10.8954 7 10 6.10457 10 5Z"
                          fill="#637381"
                        />
                        <path
                          fill-rule="evenodd"
                          clip-rule="evenodd"
                          d="M10 19C10 17.8954 10.8954 17 12 17C13.1046 17 14 17.8954 14 19C14 20.1046 13.1046 21 12 21C10.8954 21 10 20.1046 10 19Z"
                          fill="#637381"
                        />
                      </svg>
                    </button>
  
                    <div
                      x-show="openDropDown"
                      @click.outside="openDropDown = false"
                      class="shadow-card absolute right-0 top-full z-40 w-[150px] space-y-1 rounded bg-white p-2"
                    >
                      <a
                        href="{% url 'my_payslip_detail' payslip.pk %}"
                        class="text-body-color hover:bg-gray-2 w-full rounded py-1.5 px-3 text-left text-sm"
                      >
                        View
                    </a>
                      <button
                        class="text-body-color hover:bg-gray-2 w-full rounded py-1.5 px-3 text-left text-sm"
                      >
                        Download
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
  
             
  
             
             
            </div>
          </div>
        </div>
    </section>
    <!-- ====== Horizontal Menu Section End -->
    <script defer src="{% static 'js/preloader.js' %}"></script>
  </body>
</html>